name: Release

on:
  push:
    tags:
      - "v*" # Trigger only on version tags like v1.2.3

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        run: |
          ARTIFACT_NAME="${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.target }}"
          mkdir -p dist
          cp target/${{ matrix.target }}/release/${{ github.event.repository.name }} dist/
          tar -czf "$ARTIFACT_NAME.tar.gz" -C dist ${{
            github.event.repository.name
          }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: "*.tar.gz"

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
